#구글드라이브 색인
import os
os.listdir('./drive/MyDrive/Colab Notebooks/ml_data')


#결측치 확인
print(train[train.duplicated()])
print(train.isnull().sum())
msno.matrix(train,figsize=(12,5)) #흰색선이 보이지 않으므로 결측치 없음

결측치 채우기
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html

